// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMJlGkGcD5dyvhCzIY_ooXNYBObMGfmHQ',
    appId: '1:511450012191:web:c5368329342a4da311932a',
    messagingSenderId: '511450012191',
    projectId: 'dube-95226',
    authDomain: 'dube-95226.firebaseapp.com',
    storageBucket: 'dube-95226.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIQArseieMxU0hv3CJEZq8gd0dA3Zrbqs',
    appId: '1:511450012191:android:2ed40f6e273610c811932a',
    messagingSenderId: '511450012191',
    projectId: 'dube-95226',
    storageBucket: 'dube-95226.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjkRAwddrJELX2jpCVmMVvH90AmbSdhbA',
    appId: '1:511450012191:ios:33d6a98d12252e7f11932a',
    messagingSenderId: '511450012191',
    projectId: 'dube-95226',
    storageBucket: 'dube-95226.firebasestorage.app',
    iosClientId: '511450012191-vpecdm4arcoqrsjtraecnibae17qrloh.apps.googleusercontent.com',
    iosBundleId: 'com.example.dube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjkRAwddrJELX2jpCVmMVvH90AmbSdhbA',
    appId: '1:511450012191:ios:33d6a98d12252e7f11932a',
    messagingSenderId: '511450012191',
    projectId: 'dube-95226',
    storageBucket: 'dube-95226.firebasestorage.app',
    iosClientId: '511450012191-vpecdm4arcoqrsjtraecnibae17qrloh.apps.googleusercontent.com',
    iosBundleId: 'com.example.dube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMJlGkGcD5dyvhCzIY_ooXNYBObMGfmHQ',
    appId: '1:511450012191:web:0e5284fe50df04af11932a',
    messagingSenderId: '511450012191',
    projectId: 'dube-95226',
    authDomain: 'dube-95226.firebaseapp.com',
    storageBucket: 'dube-95226.firebasestorage.app',
  );

}